version: "3.9"


services:
  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_DB: url_shortener
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres-data:/var/lib/postgresql/data
    expose:
      - "5432"
    networks:
      - app-network

  backend:
    build:
      context: ./backend
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/url_shortener
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
      APP_DOMAIN: localhost:8080
    ports:
      - "8080:8080"
    networks:
      - app-network


volumes:
  postgres-data:


networks:
  app-network: