version: "3.9"


services:
  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_DB: url_shortener
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres-data:/var/lib/postgresql/data
    expose:
      - "5432"
    networks:
      - postgres-net

  redis:
    image: redis:alpine
    expose:
      - "6379"
    networks:
      - redis-net

  backend:
    build:
      context: .
    depends_on:
      postgres:
        condition: service_started
      redis:
        condition: service_started
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/url_shortener
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_REDIS_HOST: redis
    ports:
      - "8080:8080"
    networks:
      - postgres-net
      - redis-net


volumes:
  postgres-data:


networks:
  postgres-net:
  redis-net: