version: "3.9"

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: url_shortener
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    expose:
      - "5432"
    networks:
      - app-network

  redis:
    image: redis:latest
    container_name: redis
    expose:
      - "6379"
    networks:
      - app-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/url_shortener
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_REDIS_HOST: redis
    networks:
      - app-network

networks:
  app-network:
    driver: bridge