name: Workflow for Codecov
on: [push, pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
          
      - name: Install dependencies
        run: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -f backend/pom.xml
        
      - name: Run tests and collect coverage
        run: mvn -B test -f backend/pom.xml
        
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
